import '../models/navigation_model.dart';



class NavigationService {



  Future<NavigationModel> getNavigationData() async {



    // Temporary delay simulating:
    // LiDAR + UWB + SLAM processing

    await Future.delayed(

      const Duration(seconds:2),

    );




    return NavigationModel(



      // Building Information

      buildingName:

      "THERMOGUARD-X Building",



      floorNumber:

      "Floor 5",




      // Robot Location

      robotPosition:

      "Room 501",



      robotHeading:

      "North East",




      // Target Information

      firePosition:

      "Room 503",



      survivorPosition:

      "Room 505",





      // Safe Route Generated by Navigation AI

      safeRoute: [


        "Room 501",

        "Corridor A",

        "Room 502",

        "Room 503",

        "Room 505",


      ],




      distanceToTarget:

      18.5,



      estimatedArrivalTime:

      "3 Minutes",





      // Navigation Status

      navigationStatus:

      "SAFE ROUTE GENERATED",




      movementStatus:

      "Robot Moving Towards Survivor",





      // Sensor Fusion Information

      mappingSource:

      "LiDAR + UWB + SLAM",




      locationAccuracy:

      96.5,



    );


  }



}